accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'user'

urlpatterns = [
    path('signin', views.signin, name='signin'),
    path('signup', views.signup, name='signup'),
    path('logout', views.signout, name='signout'),
]

config/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [

]

erp/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('product_list', views.product_list, name='product_list'),
    path('product_create', views.product_create, name='product_create'),
    path('inbound_create', views.inbound_create, name='inbound_create'),
    path('outbound_create', views.outbound_create, name='outbound_create'),
    path('invetory', views.invetory, name='invetory'),
]

myerp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('accounts.urls')),
    path('erp/', include('erp.urls')),
    path('config/', include('config.urls')),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

config/models.py
from django.db import models

# Create your models here.

erp/models.py
from django.db import models

# Create your models here.
# model


class Product(models.Model):
    class Meta:
        db_table = 'products'

    code = models.CharField(max_length=250)
    name = models.CharField(max_length=250)
    price = models.CharField(max_length=250)
    sizes = (
        ('S', 'Small'),
        ('M', 'Medium'),
        ('L', 'Large'),
        ('F', 'Free'),
    )
    size = models.CharField(choices=sizes, max_length=1)

    # 생성될 때 stock quantity를 0으로 초기화 로직

accounts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .models import User
# Create your views here.


def signin(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            print('yeah')
            login(request, user)
        else:
            print('fail')
    return render(request, 'erp/product_list.html')


@login_required
def signout(request):
    logout(request)
    return redirect('user:signin')


def signup(request):
    if request.method == 'POST':
        print(request.POST)
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        firstname = request.POST['firstname']
        lastname = request.POST['lastname']

        user = User.objects.create_user(username, email, password)
        user.first_name = firstname
        user.last_name = lastname
        user.save()
        return redirect('user:signin')
    else:
        return render(request, 'accounts/signup.html')

config/views.py
from django.shortcuts import render

# Create your views here.

erp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

# Create your views here.


# def product_list(request):
#     pass


def product_create(request):
    pass


# def inbound_create(request):
#     pass


# def outbound_create(request):
#     pass


# def invetory(request):
#     pass

templates/accounts/signin.html
{% extends 'base.html' %}

{% block title %}
  로그인
{% endblock %}
{% block content %}
  <div class="container">
    <div class="wrap">
      {% if user.is_authenticated %}
        <h2 class="title-center">
          {{ user.username }}님 로그인 완료</h2>
      {% else %}
        <h2 class="title-center">
          로그인</h2>
        <form class="form-area" method="POST" action="signin">
          {% csrf_token %}
          <div class="form-group mt-2 mb-2">
            <label for="username">이름</label>
            <input type="text" class="form-control" id="username" name="username">
          </div>
          <div class="form-group mt-2 mb-2">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" id="password" name="password">
          </div>
          <hr>
          <div style="float: right">
            <button type="submit" class="btn btn-primary">로그인</button>
            <a href="{% url 'user:signup' %}" class="btn btn-secondary">회원가입 페이지로</a>
          </div>
        </form>
      {% endif %}
    </div>
  </div>
{% endblock %}

templates/accounts/signup.html
{% extends 'base.html' %}

{% block title %}
  회원가입
{% endblock %}
{% block content %}
  <div class="container">
    <div class="wrap">
      <h2 class="title-center">
        회원가입
      </h2>
      <form class="form-area" method="POST" action="signup">
        {% csrf_token %}
        <div class="form-group mt-2 mb-2">
          <label for="username">username</label>
          <input type="text" class="form-control" id="username" name="username" placeholder='username'>
        </div>
        <div class="form-group mt-2 mb-2">
          <label for="firstname">firstname</label>
          <input type="text" class="form-control" id="firstname" name="firstname" placeholder='firstname'>
        </div>
        <div class="form-group mt-2 mb-2">
          <label for="lastname">lastname</label>
          <input type="text" class="form-control" id="lastname" name="lastname" placeholder='lastname'>
        </div>
        <div class="form-group mt-2 mb-2">
          <label for="email">email</label>
          <input type="text" class="form-control" id="email" name="email" placeholder='example@example.com'>
        </div>
        <div class="form-group mt-2 mb-2">
          <label for="password">password</label>
          <input type="password" class="form-control" id="password" name="password" placeholder='password'>
        </div>
        <div class="form-group mt-2 mb-2">
          <label for="password2">password again</label>
          <input type="password" class="form-control" id="password2" name="password2" placeholder='password again'>
        </div>
        <hr>
        <div style="float: right">
          <button type="submit" class="btn btn-primary">회원가입</button>
          <a href="{% url 'user:signin' %}" class="btn btn-secondary">로그인 페이지로</a>
        </div>
      </form>
    </div>
  </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <title>
      {% block title %}{% endblock %}
      | spartaSNS</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    <style>
      .title-center {
        text-align: center;
        margin-top: 50px;
      }

      .wrap {
        width: 400px;
        margin: 0 auto;
      }

      .form-area {
        margin-top: 25px;
      }

      .timeline-container {
        margin-top: 25px;
      }
    </style>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <a class="navbar-brand" href="/">There is no ERP system</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">
                D'oh!
                <span class="sr-only"></span></a>
            </li>
          </ul>
        </div>
        {% if user.is_authenticated %}
          {{ user.username }}님
          <a href="{% url 'user:signout' %}">logout</a>
        {% else %}
          <form class="form-inline my-2 my-lg-0" method="GET" action="signin">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'user:signin' %}">
                  Signin
                  <span class="sr-only"></span>
                </a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'user:signup' %}">
                  Sign Up
                  <span class="sr-only"></span></a>
              </li>
            </ul>
          </form>
        {% endif %}
      </div>
    </nav>
    {% block content %}{% endblock %}

  </body>

</html>

templates/erp/inventory.html
{% extends 'base.html' %}

{% block title %}
  상품등록
{% endblock %}
{% block content %}
  <div class="container">
    <div class="wrap">
      <h2 class="title-center">
        상품등록
      </h2>
      <form class="form-area" method="POST" action="product_create">
        {% csrf_token %}
        <div class="form-group mt-2 mb-2">
          <label for="productname">product name</label>
          <input type="text" class="form-control" id="productname" name="productname" placeholder='productname'>
        </div>
        <div class="form-group mt-2 mb-2">
          <label for="productcode">product code</label>
          <input type="text" class="form-control" id="productcode" name="productcode" placeholder='productnumber'>
        </div>
        <hr>
        <div style="float: right">
          <button type="submit" class="btn btn-primary">상품등록</button>
          {% comment %} <a href="{% url 'user:signin' %}" class="btn btn-secondary">상품목록</a> {% endcomment %}
        </div>
      </form>
    </div>
  </div>
{% endblock %}